### PR TITLE
feat: fix docs and add toStaticBytes

### PR DESCRIPTION
**Pull request by yjhmelody**

### CODE REVIEW

**Comment by yjhmelody** [comment]
@MaxGraey Is there any problem with this? I fixed the documentation and added the conversion of StaticArray

**Comment by MaxGraey** [comment]
Thanks for PR. I'm just not sure how this useful (toSataticBytes). Could you fix docs in separate PR?

**Comment by yjhmelody** [comment]
> Thanks for PR. I'm just not sure how this useful (toSataticBytes). Could you fix docs in separate PR?

I used it because one of my libraries supports writing to various arrays. Then staticArray is obviously more efficient

**Comment by MaxGraey** [comment]
ok

**Pull request merged**
